### ISSUE TITLE
Convert cancelsTo key into a list.

### ISSUE THREAD

**Issue by cruzcranford** [D4RKONION/fatsfvframedatajson#1]
I would like to recommend converting cancelsTo key into a list instead of a / delimited string.  Straight forward change but here example:

Before: "cancelsTo": "sp/su/vs/vt1/vt2"
After: "cancelsTo": [ "sp", "su", "vs", "vt1", "vt2" ]

This would ease parsing of options available to certain moves.

**Comment by D4RKONION** [comment]
Fixed in 2.6.0!
